name: flutter_moapp_project
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6
  flutter_cupertino_date_picker:
  #cupertino_icons:
  numberpicker: ^0.1.7
  cloud_firestore: ^0.7.3
  firebase_auth:
  google_sign_in:
  firebase_core:
  firebase_storage:
  firebase_analytics: ^0.3.3
  image_picker: ^0.4.10

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
